site_name: RecCLI TypeScript 说明文档
site_url: https://vertsineu.github.io/reccli-ts-pages
site_description: RecCLI TypeScript 说明文档
site_author: Vertsineu

# Repository
repo_name: Vertsineu/reccli-ts-pages
repo_url: https://github.com/Vertsineu/reccli-ts-pages
edit_uri: edit/master/docs/

# Copyright
copyright: Copyright &copy; 2025 Vertsineu - <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>

# Configuration
theme:
  name: material
  language: zh
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/book-open-page-variant
  
  # 社交媒体链接
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Vertsineu

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji
  - meta
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Page tree
nav:
  - 首页: index.md
  - 安装:
    - 概述: installation/index.md
    - 本地安装:
      - Windows: installation/local/windows.md
      - Linux: installation/local/linux.md
    - 远程安装:
      - VLab: installation/remote/vlab.md
  - 使用: 
    - 概述: user-guide/index.md
    - 登录: user-guide/login.md
    - 功能介绍: user-guide/usage.md
  - 更多:
    - Q&A: more/faq.md
